version: '3'

services:
    service:
        tty: true
        container_name: service.development
        build:
            context: ../
            dockerfile: .build/dev.dockerfile
        environment:
            ENVIRONMENT: development
        volumes:
            - ../:/development
        ports:
            - 3000:3000
            - 9229:9229
