version: '3'

services:
    nginx:
        container_name: nginx
        build:
            context: .
            dockerfile: nginx.dockerfile
        ports:
            - 8080:80
        links:
            - client
            - api

    client:
        container_name: client
        build:
            context: ../client
            dockerfile: ./.build/dev.dockerfile
        volumes:
            - ../client/src:/client/src
        ports:
            - 4200:4200

    api:
        container_name: api
        build:
            context: ../server
            dockerfile: dockerfile
        ports:
            - 3000:3000
        volumes:
            - ../server/src:/app/src

        command: ["npm", "run", "dev"]

        environment:
            EXPRESS_HOST: 3000
            EXPRESS_HEADERS_ALLOW: "X-Requested-With, Content-Type, Accept, Authorization"
            EXPRESS_HEADERS_EXPOSE: "Message"
            EXPRESS_HEADERS_ORIGIN: "*"
            EXPRESS_HEADERS_METHODS: "POST, GET, PUT, DELETE, OPTIONS, PATCH"
    