version: '3'

services:
    service:
        container_name: service
        build:
            context: ../
            dockerfile: .build/prod.dockerfile
        environment:
            ENVIRONMENT: production
            EXPRESS_HOST: 3000
        ports:
            - 3000:3000
    